In [319]:
import pandas as pd
import numpy as np

# 1. to define the datasets
to divide it into train and test sets.

In [320]:
# to define the datasets

dataset = pd.read_csv('watermelon3.0a.csv', sep=',')

dataset = np.array(dataset)

# print('before')
# print(dataset)

# translate '是' and '否' into 1 and 0
for i in range(len(dataset)):
    dataset[i][3] = 1 if dataset[i][3] == '是' else 0


dataset = dataset.T
dataset = dataset[1:4]
print(dataset)
m = 17

X_dataset = dataset[0:2, :]
Y_dataset = dataset[2:3, :]

X_dataset_plus = np.array([1.0 for i in range(17)]).reshape(1, -1)
X_dataset = np.append(X_dataset, X_dataset_plus, axis=0)

print(X_dataset.shape)
print(Y_dataset.shape)

# d = int(17 * 0.7)

# d = 14

# # [0:2, 0:d] [2:3, 0:d] [0:2, d:] [2:3, d:]
# train_x = dataset[0:2, 0:d]
# train_y = dataset[2:3, 0:d]
# test_x = dataset[0:2, d:]
# test_y = dataset[2:3, d:]

# print(train_x.shape, train_y.shape, test_x.shape, test_y.shape)

# train_plus = np.array([1.0 for i in range(d)]).reshape(1, -1)
# test_plus = np.array([1.0 for i in range(17 - d)]).reshape(1, -1)

# print('train_plus shape', train_plus.shape)

# train_x = np.append(train_x, train_plus, axis=0)
# test_x = np.append(test_x, test_plus, axis=0)

# print('train_x is ', train_x)
# print('train_x shape is', train_x.shape)

# print(train_x.shape, train_y.shape, test_x.shape, test_y.shape)

[[0.697 0.774 0.634 0.608 0.556 0.403 0.481 0.437 0.666 0.243 0.245 0.343
  0.639 0.657 0.36 0.593 0.719]
 [0.46 0.376 0.264 0.318 0.215 0.237 0.149 0.211 0.091 0.267 0.057 0.099
  0.161 0.198 0.37 0.042 0.103]
 [1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]]
(3, 17)
(1, 17)


# 2. initialize the parameters

In [321]:
# initialize the parameters

def initialize_with_zeros(dim : int):
    return np.random.randn(dim, 1) * 0.1

initialize_with_zeros(3)

array([[ 0.06366559],
       [-0.08166665],
       [ 0.06891877]])

# 3. propagate

In [322]:
temp = np.array([[-0.21539082199977688, -0.2662332762116397, -0.12493609898688618,
  -0.11249979832632084, -0.04868640319866824, 0.07908169716538288,
  0.028115834322631816, 0.05458491594874759, -0.120580266543589,
  0.21140472844864, 0.24843772326704078]])
print(type(temp))
a = np.exp(temp)

print(a)


<class 'numpy.ndarray'>
[[0.80622629 0.76626036 0.8825533  0.89359753 0.95247978 1.08229274
  1.02851481 1.05610215 0.88640594 1.23541226 1.28202098]]


In [323]:
m = 11
Beta = np.random.randn(3, 1)
X = np.random.randn(3, m)
Y = np.random.randn(1, m)

temp = -1 * Y * np.dot(Beta.T, X) + np.log(1 + np.exp(np.dot(Beta.T, X)))
print(temp.shape)

cost = np.sum(-1 * Y * np.dot(Beta.T, X) + np.log(1 + np.exp(np.dot(Beta.T, X))))

print(cost)

(1, 11)
14.530478503148341


In [324]:
def propagate(Beta:np.ndarray, X:np.ndarray, Y:np.ndarray):
    cost = np.sum(-1.0 * Y * np.dot(Beta.T, X) + np.log(1.0 + np.exp(np.dot(Beta.T, X).astype(float))))
    p1 = np.exp(np.dot(Beta.T, X).astype(float)) / (1.0 + np.exp(np.dot(Beta.T, X).astype(float)))
    db = -1 * np.sum(X * (Y - p1))
    ddb = np.sum(np.dot(X.T, X) * p1 * (1 - p1))

    grads = {
        'db': db,
        'ddb': ddb
    }

    return grads, cost

# 4. Optimize

In [325]:
5**-1

0.2

In [326]:
def optimize(Beta:np.ndarray, X:np.ndarray, Y:np.ndarray, num_iterations=1000):
    costs = []
    for i in range(num_iterations):
        grads, cost = propagate(Beta, X, Y)

        db = grads['db']
        ddb = grads['ddb']

        Beta = Beta - (ddb**-1) * db
        
        if i % 100 == 0:
            costs.append(cost)
        
        if i % 100 == 0:
            print('Now cost is ', cost)

    parameters = {
        'Beta': Beta,
        'costs': costs
    }

    return parameters

# 5. Prediction

In [327]:
def predict(Beta:np.ndarray, X)->np.ndarray:

    m = X.shape[1]
    y_prediction = np.zeros((1, m))

    Y = np.dot(Beta.T, X)

    for i in range(m):
        if Y[0, i] >= 0.5:
            y_prediction[0, i] = 1
    
    return y_prediction

In [328]:
y_prediction = np.zeros((1, m))

print(y_prediction.shape)

(1, 11)


# 6. Model construction

In [329]:
a = np.array([1, 1, 1, 1, 1, 1, 1, 1])
b = np.array([1, 1, 1, 1, 1, 0, 0, 0])

c = np.sum(a == b)

print(c)

5


In [330]:
data = train_x
print(data)
newdata = np.delete(data, 0, 1)
print(newdata)

[[0.697 0.774 0.634 0.608 0.556 0.403 0.481 0.437 0.666 0.243 0.245 0.343
  0.639 0.657 0.36 0.593]
 [0.46 0.376 0.264 0.318 0.215 0.237 0.149 0.211 0.091 0.267 0.057 0.099
  0.161 0.198 0.37 0.042]
 [1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0]]
[[0.774 0.634 0.608 0.556 0.403 0.481 0.437 0.666 0.243 0.245 0.343 0.639
  0.657 0.36 0.593]
 [0.376 0.264 0.318 0.215 0.237 0.149 0.211 0.091 0.267 0.057 0.099 0.161
  0.198 0.37 0.042]
 [1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0]]


In [331]:
def model(train_x:np.ndarray, train_y:np.ndarray, test_x:np.ndarray, test_y:np.ndarray, num_iterations=1000):
    dim = 3
    Beta = initialize_with_zeros(dim)
    parameters = optimize(Beta, train_x, train_y, num_iterations)

    Beta = parameters['Beta']
    costs = parameters['costs']

    y_prediction_train = predict(Beta, train_x)
    y_prediction_test = predict(Beta, test_x)

    correct_train = np.sum(y_prediction_train == train_y) / train_y.shape[1]
    correct_test = np.sum(y_prediction_test == test_y) / test_y.shape[1]

    # print('y_prediction_train is', correct_rate_train)
    # print('y_prediction_test is', correct_rate_test)

    # print('correct_rate_train is {} %'.format(correct_rate_train * 100))
    # print('correct_rate_test is {} %'.format(correct_rate_test * 100))

    d = {
        'correct_train': correct_train,
        'correct_test': correct_test,
        'y_prediction_train': y_prediction_train,
        'y_prediction_test': y_prediction_test,
        'Beta': Beta, 
        'costs': costs
    }
    
    return d

# 7. Over, But is it ok?

In [332]:
m = 17
train_correct_sum = 0
test_correct_sum = 0

for i in range(m):
    train_x = np.delete(X_dataset, i, 1)
    train_y = np.delete(Y_dataset, i, 1)
    test_x = X_dataset[:, i].reshape(-1, 1)
    test_y = Y_dataset[:, i].reshape(-1, 1)
    # print('train_x is ', train_x.shape)
    # print('train_y is ', train_y.shape)
    # print('test_x is ', test_x.shape)
    # print('test_y is ', test_y.shape)
    logistic_regression = model(train_x, train_y, test_x, test_y, 1000)
    train_correct_sum += logistic_regression['correct_train']
    test_correct_sum += logistic_regression['correct_test']

print('train correct rate is {}%'.format(train_correct_sum / m * 100))
print('test correct rate is {}%'.format(test_correct_sum / m * 100))
    


Now cost is  11.081451743531144
Now cost is  11.042785179224305
Now cost is  11.042785179224303
Now cost is  11.042785179224307
Now cost is  11.042785179224307
Now cost is  11.042785179224307
Now cost is  11.042785179224307
Now cost is  11.042785179224307
Now cost is  11.042785179224307
Now cost is  11.042785179224307
Now cost is  11.398344720197649
Now cost is  11.148240695060888
Now cost is  11.14824069506088
Now cost is  11.148240695060878
Now cost is  11.148240695060878
Now cost is  11.148240695060878
Now cost is  11.148240695060878
Now cost is  11.148240695060878
Now cost is  11.148240695060878
Now cost is  11.148240695060878
Now cost is  11.511145042320198
Now cost is  11.117577962550575
Now cost is  11.117577962550566
Now cost is  11.117577962550568
Now cost is  11.117577962550568
Now cost is  11.117577962550568
Now cost is  11.117577962550566
Now cost is  11.117577962550566
Now cost is  11.117577962550566
Now cost is  11.117577962550566
Now cost is  11.188817086649145
Now cost 